- hosts: localhost
  tasks:
    - ec2:
        image: "ami-5b673c34"
        region: "ap-south-1"
        state: present
        wait: True
        group: "launch-wizard-1"
        aws_access_key: "" 
        aws_secret_key: ""
        #assign_public_ip: yes
        instance_type: "t2.micro"
        #volumes: 
         #   - device_name: "/dev/sda1"
          #  - volume_size: "10"
           # - iops: "100"
           # - delete_on_termination: true
           # - volume_type: "root"
        #instance_tags: '{"name": "rhel"}' 
  environment:
     - PYTHONPATH: "/usr/local/lib/python3.6/site-packages"
